---

- hosts: all
  tasks:
    - name: "Checking operating system version"
      assert:
        that: ansible_distribution_release == 'bookworm'
        fail_msg: "This Ansible playbook is only supported on Debian Bookworm."
        success_msg: "Debian Bookworm found."

- hosts: all
  roles:
    - packages
    - common
    - bind9
    - nginx
    - certbot
    - database
    - postfix
    - dovecot
    - rspamd

- hosts: all
  tasks:
    - debug:
        msg:
          - "Installation complete."
          - ""
          - "Domain        : {{ mail_domain }}"
          - "FQDN          : {{ mail_fqdn }}"
          - "Public IPv4   : {{ trusty_networks.ipv4_address }}"
          - "Public IPv6   : {{ trusty_networks.ipv6_address }}"
          - "Internal IPv4 : {{ trusty_networks.lan_ipv4 }}"
          - "DKIM selector : {{ mail_dkim_selector }}"
          - "Mail location : {{ mail_data_rootdir }}"
