---

- hosts: all
  tasks:
    - name: "Checking operating system version"
      assert:
        that: ansible_distribution_release == 'bookworm'
        fail_msg: "This Ansible playbook is only supported on Debian Bookworm."
        success_msg: "Debian Bookworm found."

- hosts: all
  roles:
    - role: packages
      tags: packages
    - role: common
      tags: common
    - role: bind9
      tags: bind9
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
    - role: database
      vars:
        mysql_mailserver_dbusername: "{{ mysql.mailserver.username }}"
        mysql_mailserver_dbpasswd: "{{ mysql.mailserver.password }}"
        mysql_mailserver_dbname: "{{ mysql.mailserver.dbname }}"
        mysql_mailserver_dbhost: "{{ mysql.mailserver.host }}"
      tags: database
    - role: postfix
      tags: postfix
    - role: dovecot
      tags: dovecot
    - role: rspamd
      vars:
        rspamd_web_access: "{{ rspamd_web_access }}"
      tags: rspamd

- hosts: all
  tasks:
    - debug:
        msg:
          - "Installation complete."
          - ""
          - "Domain        : {{ mail_domain }}"
          - "FQDN          : {{ mail_fqdn }}"
          - "Public IPv4   : {{ trusty_networks.ipv4_address }}"
          - "Public IPv6   : {{ trusty_networks.ipv6_address }}"
          - "Internal IPv4 : {{ trusty_networks.lan_ipv4 }}"
          - "DKIM selector : {{ mail_dkim_selector }}"
          - "Mail location : {{ mail_data_rootdir }}"
